name: Manually execute
on:
  workflow_dispatch:
    inputs:
      source:
        description: 'Source (gigazine, syobocal, annict)'
        required: true
        default: 'gigazine'
      format:
        description: 'Output format'
        required: true
        default: 'markdown'
      sort:
        description: 'Sort rule'
        required: true
        default: 'time'
      url:
        description: 'Target URL (in Gigazine)'
        required: false

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: 1.x
      - name: Execute
        run: |
          case ${{ github.event.inputs.source }} in
            "gigazine" ) go run main.go ${{ github.event.inputs.source }} \
                           -url ${{ github.event.inputs.url }} \
                           -format ${{ github.event.inputs.format }} \
                           -sort ${{ github.event.inputs.sort }} ;;

            "syobocal" ) go run main.go ${{ github.event.inputs.source }} \
                           -format ${{ github.event.inputs.format }} \
                           -sort ${{ github.event.inputs.sort }} ;;

            "annict" ) echo "Annict source need Annict token. It's secret value. So, please execute on your machine."
                       exit 1 ;;
            * ) ${{ github.event.inputs.source }} is not support source.
          esac

