name: test
on:
  push:
    branches:
      - "**"
  pull_request: {}

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-18.04
    steps:
      - name: setup go
        uses: actions/setup-go@v3
        with:
          go-version: 1.x
      - name: checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 1
#      - name: lint
#        run: |
#          GO111MODULE=off GOBIN=$(pwd)/bin go get golang.org/x/lint/golint
#          bin/golint -set_exit_status ./...
#      - name: vet
#        run: |
#          go vet ./...
      - name: build
        run: go build .
      - name: test
        run: |
          go test -v ./...